'type: breaking':
  - head-branch: ['^breaking/', '^breaking-']
'type: feature':
  - head-branch: ['^feature/', '^features/', '^feat/', '^feature-']
'type: improvement':
  - head-branch: ['^improve/', '^improvement/', '^improvements/', '^impr/', '^improvement-']
'type: automation':
  - head-branch: ['^automation/', '^automation-']
'type: documentation':
  - head-branch: ['^doc/', '^docs/', '^documentation/', '^documentations/', '^documentation-']

# `skip-changelog` is applied manually for changes excluded from release notes.
